apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: pipeline-productpage-run-
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: pipeline-productpage
  resources:
    - name: git
      resourceRef:
        name: git-bookinfo-productpage
    - name: image
      resourceRef:
        name: registry-bookinfo-productpage
